const $=s=>document.querySelector(s);let briefing=null;
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function list(a){return(a||[]).map(x=>`<li>${esc(x)}</li>`).join("")}
function toast(t){$("#toast").textContent=t;$("#toast").style.display="block";setTimeout(()=>$("#toast").style.display="none",2300)}
function tab(id){document.querySelectorAll(".panel").forEach(p=>p.classList.remove("active"));$("#"+id).classList.add("active");document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.tab===id));window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>tab(n.dataset.tab));
function mh(icon,title){return `<div class="mini-head"><div class="mini-icon">${icon}</div><h3>${title}</h3></div>`}
function render(d){briefing=d;$("#dashboard-empty").classList.add("hidden");$("#results").classList.remove("hidden");const c=Math.max(0,Math.min(100,Number(d.confidence)||0));
const cards=`<div class="result-title"><div><h2>2. Resultados da Apuração</h2><p>Confira abaixo os principais pontos levantados pela IA.</p></div><span class="pill">● Pauta analisada</span></div>
<div class="cards"><article class="card mini">${mh("♢","Radar de Confiabilidade")}<div class="confidence"><div class="donut" style="--p:${c}"><b>${c}%</b></div><div class="legend"><div><i class="dot green-dot"></i>Confirmado &nbsp; ${d.confirmed?.length||0}</div><div><i class="dot yellow-dot"></i>Estimativa / Projeção &nbsp; ${d.estimates?.length||0}</div><div><i class="dot red-dot"></i>Não confirmado &nbsp; ${d.unconfirmed?.length||0}</div><div><i class="dot red-dot"></i>Conflitos &nbsp; ${d.conflicts?.length||0}</div></div></div><p>${esc(d.summary)}</p></article>
<article class="card mini">${mh("↗","Principais Fontes")}${(d.sources||[]).slice(0,4).map(s=>`<div class="source-line"><b>${esc(s.title)}</b><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.url)}</a></div>`).join("")||"<p>Nenhuma fonte retornada.</p>"}</article>
<article class="card mini">${mh("▥","Dados Importantes")}<div class="data-line">◉ <div><span>Headline</span><b>${esc(d.headline||"—")}</b></div></div><div class="data-line">◉ <div><span>Status</span><b>${esc(d.status||"—")}</b></div></div><div class="data-line">◉ <div><span>Confiança</span><b>${c}%</b></div></div></article></div>
<div class="wide-grid"><article class="card mini purple-card">${mh("♧","Quem Ouvir")}<ul>${list(d.hear)}</ul><button class="linkbtn">Ver lista completa →</button></article>
<article class="card mini yellow-card">${mh("⚠","O que Checar")}<ul>${list(d.check)}</ul><button class="linkbtn">Ver mais detalhes →</button></article>
<article class="card mini green-card">${mh("◎","Melhor Ângulo Jornalístico")}<p>${esc(d.angle)}</p><button class="linkbtn" id="goWrite">Ver ângulo completo →</button></article></div>
<div class="bottom-grid"><article class="card">${mh("▤","Estrutura Sugerida da Matéria")}<ol class="number-list">${list(d.structure)}</ol></article><article class="card risk">${mh("⚠","Riscos e Observações")}<ul>${list(d.risks)}</ul><div class="notice">💡 O Jornalista AI é um assistente de apuração.<br>A decisão editorial final é sempre sua.</div></article></div>
<div class="actions"><div>▣ <b>Copiar briefing completo</b><small>Salve todo o resumo da apuração em um só clique.</small></div><button id="copy">Gerar rascunho da matéria →</button></div>`;
$("#results").innerHTML=cards;$("#write").disabled=false;$("#copy").onclick=()=>{navigator.clipboard?.writeText(JSON.stringify(d,null,2));toast("Briefing copiado")};$("#goWrite").onclick=()=>tab("redacao");$("#apurarContent").innerHTML=cards;$("#apurarContent").querySelector("#copy")?.addEventListener("click",()=>toast("Briefing copiado"))}
$("#analyze").onclick=async()=>{const topic=$("#topic").value.trim();if(!topic)return toast("Digite o tema da pauta.");$("#analyze").disabled=true;$("#analyze").textContent="⟳  APURANDO…";try{const r=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic,area:$("#area").value,format:$("#format").value,sources:$("#sources").value})});const d=await r.json();if(!r.ok)throw Error(d.error||"Erro");render(d)}catch(e){toast(e.message)}finally{$("#analyze").disabled=false;$("#analyze").textContent="⌕  Pesquisar e Apurar  →"}};
$("#write").onclick=async()=>{if(!briefing)return;$("#write").disabled=true;$("#draft").textContent="Gerando rascunho…";try{const r=await fetch("/api/write",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({briefing})});const d=await r.json();if(!r.ok)throw Error(d.error);$("#draft").textContent=d.text;tab("redacao")}catch(e){toast(e.message)}finally{$("#write").disabled=false}};
$("#factBtn").onclick=async()=>{const text=$("#factText").value.trim();if(!text)return toast("Cole um texto para checar.");$("#factBtn").disabled=true;$("#factOut").textContent="Checando…";try{const r=await fetch("/api/factcheck",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});const d=await r.json();if(!r.ok)throw Error(d.error);$("#factOut").textContent=d.text}catch(e){toast(e.message)}finally{$("#factBtn").disabled=false}};