const $=s=>document.querySelector(s);let briefing=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const list=a=>(a||[]).map(x=>`<li>${esc(x)}</li>`).join("")||"<li>—</li>";
function toast(t){const x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),9000)}
function showError(t){toast(t); const box=$("#results"); if(box){box.classList.remove("hidden"); box.innerHTML=`<div class="card error-card"><h2>⚠️ A apuração não foi concluída</h2><p>${esc(t)}</p><p><b>As buscas externas são independentes do Gemini.</b> Se o problema for cota da IA, as fontes ainda poderão ser consultadas pelo teste de busca.</p></div>`;}}
function tab(id){document.querySelectorAll(".panel").forEach(p=>p.classList.remove("active"));$("#"+id).classList.add("active");document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.tab===id));window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>tab(n.dataset.tab));
function mh(icon,title){return `<div class="mini-head"><div class="mini-icon">${icon}</div><h3>${title}</h3></div>`}
function statusClass(s){s=String(s||"").toUpperCase();return /CONFLITO/.test(s)?"danger":/NÃO|NAO/.test(s)?"warn":"ok"}
function render(d){
 briefing=d;
 if(d.partial){
   const sources=(d.sources||[]).map(s=>`<div class="source-line"><div><b>${esc(s.title)}</b><small>${esc(s.tier||"Fonte")}</small></div><a href="${esc(s.url)}" target="_blank" rel="noopener">Abrir fonte ↗</a><p>${esc(s.why||"")}</p></div>`).join("")||"<p>Nenhuma fonte retornada.</p>";
   $("#dashboard-empty").classList.add("hidden"); $("#results").classList.remove("hidden");
   $("#results").innerHTML=`<div class="card error-card"><h2>⚠️ Pesquisa concluída, análise da IA indisponível</h2><p>${esc(d.note||"O Gemini não conseguiu concluir a análise.")}</p><p><b>Boa notícia:</b> a busca externa funcionou e estas são as fontes encontradas. Elas ainda precisam de revisão humana.</p><div class="mini-head"><h3>Fontes encontradas</h3></div>${sources}</div>`;
   return;
 }
$("#dashboard-empty").classList.add("hidden");$("#results").classList.remove("hidden");const c=Math.max(0,Math.min(100,Number(d.confidence)||0));const st=d.primary_status||d.status||"—";
 const sources=(d.sources||[]).slice(0,6).map(s=>`<div class="source-line"><div><b>${esc(s.title)}</b><small>${esc(s.tier||"Fonte")}</small></div><a href="${esc(s.url)}" target="_blank" rel="noopener">Abrir fonte ↗</a><p>${esc(s.why||"")}</p></div>`).join("")||"<p>Nenhuma fonte retornada.</p>";
 const cards=`<div class="result-title"><div><h2>2. Resultados da Apuração</h2><p>Apuração em camadas: fato principal, evidências, contexto e conflitos reais.</p></div><span class="pill">● Pauta analisada</span></div>
 <div class="cards"><article class="card mini">${mh("♢","Radar de Confiabilidade da Pauta")}<div class="confidence"><div class="donut" style="--p:${c}"><b>${c}%</b></div><div class="legend"><strong class="status-badge ${statusClass(st)}">${esc(st)}</strong><div><i class="dot green-dot"></i>Confirmados ${d.confirmed?.length||0}</div><div><i class="dot yellow-dot"></i>Estimativas ${d.estimates?.length||0}</div><div><i class="dot red-dot"></i>Não confirmados ${d.unconfirmed?.length||0}</div><div><i class="dot red-dot"></i>Conflitos diretos ${d.conflicts?.length||0}</div></div></div><p><b>Evidência principal:</b> ${esc(d.primary_evidence||"—")}</p><p>${esc(d.summary)}</p></article>
 <article class="card mini">${mh("✓","Evidências Diretas")}<ul>${list(d.direct_evidence)}</ul><div class="section-label">Qualidade das fontes</div><p>${esc(d.source_quality||"—")}</p></article>
 <article class="card mini">${mh("▥","Dados Importantes")}<div class="data-line">◉ <div><span>Headline</span><b>${esc(d.headline||"—")}</b></div></div><div class="data-line">◉ <div><span>Status editorial</span><b>${esc(st)}</b></div></div><div class="data-line">◉ <div><span>Confiança</span><b>${c}%</b></div></div></article></div>
 <div class="wide-grid"><article class="card mini purple-card">${mh("↗","Principais Fontes")}${sources}</article><article class="card mini yellow-card">${mh("◇","Contexto — não confundir com conflito")}<ul>${list(d.context_evidence)}</ul></article><article class="card mini green-card">${mh("⚠","Conflitos Reais")}${d.contradiction_evidence?.length?`<ul>${list(d.contradiction_evidence)}</ul>`:`<p>🟢 Nenhuma contradição direta identificada.</p>`}</article></div>
 <div class="bottom-grid"><article class="card">${mh("🧪","Teste de Sanidade")}<ul>${list(d.sanity_check)}</ul><div class="notice">O radar considera a pauta principal, não detalhes históricos isolados.</div></article><article class="card">${mh("◎","Melhor Ângulo Jornalístico")}<p>${esc(d.angle)}</p><button class="linkbtn" id="goWrite">Ver ângulo completo →</button></article></div>
 <div class="bottom-grid"><article class="card">${mh("▤","Estrutura Sugerida da Matéria")}<ol class="number-list">${list(d.structure)}</ol></article><article class="card risk">${mh("⚠","Riscos e Observações")}<ul>${list(d.risks)}</ul><div class="notice">💡 Busca externa + Gemini gratuito. O Jornalista AI é um assistente de apuração; a decisão editorial final é sempre sua.</div></article></div>
 <div class="actions"><div>▣ <b>Apuração pronta para revisão</b><small>O rascunho respeitará o grau de confirmação das informações.</small></div><button id="copy">Copiar briefing →</button><button id="writeNow">Gerar rascunho da matéria →</button></div>`;
 $("#results").innerHTML=cards;$("#apurarContent").innerHTML=cards;$("#write").disabled=false;
 document.querySelectorAll("#copy").forEach(b=>b.onclick=()=>{navigator.clipboard?.writeText(JSON.stringify(d,null,2));toast("Briefing copiado")});
 document.querySelectorAll("#goWrite,#writeNow").forEach(b=>b.onclick=()=>{tab("redacao");setTimeout(()=>$("#write")?.click(),100)});
}
$("#analyze").onclick=async()=>{const topic=$("#topic").value.trim();if(!topic)return toast("Digite o tema da pauta.");$("#analyze").disabled=true;$("#analyze").textContent="⟳  APURANDO EM CAMADAS…";try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),45000);const r=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic,area:$("#area").value,format:$("#format").value,sources:$("#sources").value}),signal:controller.signal});clearTimeout(timer);const d=await r.json();if(!r.ok)throw Error(d.error||"O servidor não conseguiu concluir a apuração.");render(d)}catch(e){showError(e.name==="AbortError"?"A apuração demorou mais de 45 segundos. A busca externa pode estar lenta ou a IA pode estar sem cota.":e.message)}finally{$("#analyze").disabled=false;$("#analyze").textContent="⌕  Pesquisar e Apurar  →"}};
$("#write").onclick=async()=>{if(!briefing)return;$("#write").disabled=true;$("#draft").textContent="Gerando rascunho com as regras da apuração…";try{const r=await fetch("/api/write",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({briefing})});const d=await r.json();if(!r.ok)throw Error(d.error);$("#draft").textContent=d.text;tab("redacao")}catch(e){toast(e.message)}finally{$("#write").disabled=false}};
$("#factBtn").onclick=async()=>{const text=$("#factText").value.trim();if(!text)return toast("Cole um texto para checar.");$("#factBtn").disabled=true;$("#factOut").textContent="Checando afirmação por afirmação…";try{const r=await fetch("/api/factcheck",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});const d=await r.json();if(!r.ok)throw Error(d.error);$("#factOut").textContent=d.text}catch(e){toast(e.message)}finally{$("#factBtn").disabled=false}};
